import Head from "next/head";
import Image from "next/image";
import { useEffect, useState, useContext } from "react";

// import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";
import { fetchPizzaStores } from "../lib/pizza-stores";
import useTrackLocation from "../hooks/use-track-location";
import { ACTION_TYPES, StoreContext } from "./_app";

export async function getStaticProps(context) {
  const pizzaStores = await fetchPizzaStores();

  return {
    props: {
      coffeeStores: pizzaStores,
    },
  };
}

export default function Home(props) {
  const { handleTrackLocation, locationErrorMsg, isFindingLocation } =
    useTrackLocation();

  const { dispatch, state } = useContext(StoreContext);
  const { pizzaStores, latLong } = state;

  // const [pizzaStores, setPizzaStores] = useState("");
  const [pizzaStoresError, setPizzaStoresError] = useState("");

  useEffect(() => {
    const fetchData = async () => {
      if (latLong) {
        try {
          const fetchedPizzaStores = await fetchPizzaStores(latLong, 15);
          console.log(fetchedPizzaStores);
          // setPizzaStores(fetchedPizzaStores);
          dispatch({
            type: ACTION_TYPES.SET_PIZZA_STORES,
            payload: { pizzaStores: fetchedPizzaStores },
          });
        } catch (error) {
          console.log(error);
          setPizzaStoresError(error.message);
        }
      }
    };
    fetchData();
  }, [latLong]);

  const handleOnBannerBtnClick = () => {
    handleTrackLocation();
    console.log({ latLong, locationErrorMsg });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={
            isFindingLocation ? "Locating . . ." : "View stores nearby"
          }
          handleOnClick={handleOnBannerBtnClick}
        />
        {locationErrorMsg && <p>Something went wrong: {locationErrorMsg}</p>}
        {pizzaStoresError && <p>Something went wrong: {pizzaStoresError}</p>}
        <div className={styles.heroImage}>
          <Image
            src="/static/coffee.png"
            width={440}
            height={300}
            priority={true}
            alt="Hero Image"
          />
        </div>
        {pizzaStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Stores near me</h2>

            <div className={styles.cardLayout}>
              {pizzaStores.map((pizzaStores) => {
                return (
                  <Card
                    className={styles.card}
                    key={pizzaStores.id}
                    name={pizzaStores.name}
                    imgUrl={
                      pizzaStores.imgUrl ||
                      "https://images.unsplash.com/photo-1476283721796-dd935b062838?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80"
                    }
                    href={`/coffee-stores/${pizzaStores.id}`}
                  />
                );
              })}
            </div>
          </div>
        )}

        {props.coffeeStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Karachi Stores</h2>

            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStores) => {
                return (
                  <Card
                    className={styles.card}
                    key={coffeeStores.id}
                    name={coffeeStores.name}
                    imgUrl={
                      coffeeStores.imgUrl ||
                      "https://images.unsplash.com/photo-1476283721796-dd935b062838?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80"
                    }
                    href={`/coffee-stores/${coffeeStores.id}`}
                  />
                );
              })}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
