import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import Banner from "../components/banner";
import Card from "../components/card";
import { fetchPizzaStores } from "../lib/pizza-stores";

// import coffeeStoresData from '../data/coffee-store.json'

export async function getStaticProps(context) {
  const pizzaStores = await fetchPizzaStores();

  return {
    props: {
      coffeeStores: pizzaStores,
    },
  };
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log("Button clicked");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/coffee.png"
            width={440}
            height={300}
            priority={true}
            alt="Hero Image"
          />
        </div>

        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Karachi Stores</h2>

            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStores) => {
                return (
                  <Card
                    className={styles.card}
                    key={coffeeStores.fsq_id}
                    name={coffeeStores.name}
                    imgUrl={
                      coffeeStores.imgUrl ||
                      "https://images.unsplash.com/photo-1476283721796-dd935b062838?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80"
                    }
                    href={`/coffee-stores/${coffeeStores.fsq_id}`}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
